# Generated by Django 5.0.6 on 2024-06-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocontent',
            name='audio_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='image_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
