# Generated by Django 5.0.6 on 2024-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='motto',
            field=models.CharField(default='这个人很懒，什么都没有留下', max_length=100),
        ),
    ]
