# Generated by Django 5.0.6 on 2024-06-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audiocontent_audio_path_imagecontent_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocontent',
            name='audio_path',
        ),
        migrations.RemoveField(
            model_name='imagecontent',
            name='image_path',
        ),
    ]
