# Generated by Django 5.0.6 on 2024-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_audiocontent_audio_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiocontent',
            name='local_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagecontent',
            name='local_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
