# Generated by Django 5.0.6 on 2024-06-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_audiocontent_audio_alter_imagecontent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_note',
            name='created_at',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user_note',
            name='updated_at',
            field=models.CharField(max_length=255),
        ),
    ]
