# Generated by Django 5.0.6 on 2024-06-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_folder_user_note_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='nickname',
            field=models.CharField(blank=True, default='取个昵称吧', max_length=30, null=True),
        ),
    ]
