# Generated by Django 5.0.6 on 2024-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_info_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_note',
            name='folder',
        ),
        migrations.AddField(
            model_name='user_note',
            name='tag',
            field=models.CharField(default='学习', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User_folder',
        ),
    ]
