# Generated by Django 5.0.6 on 2024-06-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_user_note_folder_user_note_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_note',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
